Add a workflow for github page and wasm compatible example
PPakalns/egui_taffy pull request #8
Opened 2024-12-31 09:55 UTC by TheRustyPickle

Hello @PPakalns! I’ve updated the example to work with WASM and added a workflow that deploys a GitHub Page for the example UI. Once it’s merged, you can set it up by going to the repository settings => Pages => and selecting the `gh-pages` branch. This will create a page like this: https://therustypickle.github.io/egui_taffy/

Please let me know if there’s anything you’d like me to adjust or if this isn’t something you were looking for. Thanks!

2025-01-01 17:20 UTC, PPakalns commented
Great idea!  This is useful.

Did you use some kind of example/template for these changes. Can you share link to it?

Will take some time to review this as I want to make sure that everything is correct.

2025-01-01 17:33 UTC, TheRustyPickle commented
I did something similar for two other projects of mine, I mostly copied from there. Originally the `index.html`, wasm code is from the repo here: 

https://github.com/emilk/eframe_template

2025-01-01 17:35 UTC, PPakalns requested changes

2025-01-01 17:35 UTC, PPakalns commented on example/index.html
> +<!doctype html>
Can wasm build relevant files be moved in separate subdirectory?

2025-01-01 17:35 UTC, PPakalns commented on example/Cargo.toml
> +[package]
Is separate Cargo.toml file needed? Can Cargo.toml file from root directory be used?

2025-01-01 17:35 UTC, PPakalns commented on example/Cargo.lock
> +# This file is automatically @generated by Cargo.
The same question as with Cargo.toml. Why separate Cargo.lock is needed?

2025-01-01 17:35 UTC, PPakalns commented on Cargo.toml
> -[dev-dependencies]
Can this be controlled with cfg(...) for wasm / desktop builds?

2025-01-01 17:35 UTC, PPakalns commented on example/src/main.rs
> +#[cfg(target_arch = "wasm32")]
To avoid duplicated code. `MyApp` can be reused in desktop and wasm main functions.

2025-01-02 05:50 UTC, TheRustyPickle commented on example/index.html
> +<!doctype html>
From what I know, this is not possible. Trunk expects the `Cargo.toml` file in the same directory to compile it to wasm. I was getting an error like this where the `index.html` file is in the folder `html`

```
Caused by:
    0: error getting cargo metadata
    1: `cargo metadata` exited with an error: error: manifest path `path/project/html/Cargo.toml` does not exist
```

I couldn't find any specific config to change this

2025-01-02 05:55 UTC, TheRustyPickle commented on example/Cargo.toml
> +[package]
Before deploying via GitHub pages, `trunk` CLI is used to compile. Essentially I have turned the example folder into a full bin project for compatibility with trunk. Without a separate `Cargo.toml` the example cannot be compiled to wasm to serve it.

2025-01-02 05:58 UTC, TheRustyPickle commented on example/Cargo.lock
> +# This file is automatically @generated by Cargo.
Let me know if my comment on cargo.toml answers it

2025-01-02 05:59 UTC, TheRustyPickle commented on Cargo.toml
> -[dev-dependencies]
I couldn't find any specific config that will allow Trunk to use dev dependencies

2025-01-02 06:13 UTC, TheRustyPickle commented on example/src/main.rs
> +#[cfg(target_arch = "wasm32")]
Let me know if the latest changes satisfy this.

2025-01-11 14:37 UTC, PPakalns commented
Squashed and resolved merge conflicts in
https://github.com/PPakalns/egui_taffy/commit/ef83a9091d6117050a972e3ebb7066d2556f8ecb

After that did some reorganization to minimize exposure to web demo related code to single subdirectory.

Thank you for this PR.  :100:

2025-01-11 14:37 UTC, closed without merging